version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: 781327374347.dkr.ecr.eu-west-1.amazonaws.com/enx-dataschience-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=qEmHuWobGHr2voNE06ab7QPX14QzUTxcpD1IFhepV-I=
            - AWS_DEFAULT_REGION=eu-west-1
            - AIRFLOW_USERNAME=dev
            - AIRFLOW_PASSWORD=dev
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
            - ./tasks:/usr/local/airflow/tasks
            - ~/.aws:/usr/local/airflow/.aws
            - ./init:/init
            - ./modules:/modules/modules
        ports:
            - "80:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
