version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=airflow
        ports:
          - "5432:5432"

    webserver:
        image: ritchie46/enx-airflow:0.3
        restart: "always"
        depends_on:
            - postgres
        environment:
            - FERNET_KEY=${FERNET_KEY}
            - AWS_DEFAULT_REGION=eu-west-1
            - AIRFLOW_USERNAME=${AIRFLOW_USERNAME}
            - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./config:/config
            - ./plugins:/usr/local/airflow/plugins
            - ./tasks:/usr/local/airflow/tasks
            - ~/.aws:/usr/local/airflow/.aws
            - ./modules:/modules/modules
            # Comment out the line below on windows.
            - ./init:/init
        ports:
            - "80:8080"
        command: /init/entrypoint.sh
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
